import Head from 'next/head'
import { Layout } from '../components/Layout'
import styles from '../shared/styles/page.module.css'

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1>About</h1>
        </main>
      </Layout>
    </>
  )
}
